const fusions = [
    ["air", "", ""],
    ["earth", "", ""],
    ["acid", "rain rain", "smoke"],
    ["acid", "rain", "smog"],
    ["airplane", "bird", "steel"],
    ["airplane", "bird", "metal"],
    ["alarm", "clock clock", "sound"],
    ["alcohol", "fruit", "time"],
    ["alcohol", "juice", "time"],
    ["algae", "water", "plant"],
    ["algae", "sea", "plant"],
    ["algae", "ocean", "plant"],
    ["alien", "life", "space"],
    ["allergy", "human", "dust"],
    ["alligator", "lizard", "swamp"],
    ["alligator", "lizard", "river"],
    ["alpaca", "mountain", "sheep"],
    ["ambulance", "car", "hospital"],
    ["ambulance", "car", "doctor"],
    ["angel", "human", "bird"],
    ["angler", "human", "fishing rod"],
    ["ant", "grass", "wild animal"],
    ["ant", "wild animal", "sugar"],
    ["antarctica", "snow", "desert"],
    ["antarctica", "ice", "desert"],
    ["aquarium", "water", "glass"],
    ["aquarium", "glass", "fish"],
    ["archipelago", "isle", "isle"],
    ["armadillo", "wild animal", "armour"],
    ["armour", "tool", "metal"],
    ["armour", "tool", "steel"],
    ["ash", "volcano", "energy"],
    ["astronaut", "human", "moon"],
    ["astronaut", "rocket", "human"],
    ["astronaut", "human", "space station"],
    ["astronaut", "human", "space"],
    ["astronaut", "ice cream ice cream", "astronaut"],
    ["atmosphere", "air", "pressure"],
    ["atmosphere", "sky", "pressure"],
    ["atomic", "bomb energy", "explosion"],
    ["aurora", "sun", "antarctica"],
    ["aurora", "sky", "antarctica"],
    ["aurora", "antarctica", "atmosphere"],
    ["avalanche", "energy", "snow"],
    ["axe", "blade", "wood"],
    ["bacon", "pig", "fire"],
    ["bacteria", "swamp", "life"],
    ["baker", "human", "flour"],
    ["baker", "human", "bread"],
    ["baker", "human", "dough"],
    ["bakery", "house", "baker"],
    ["bakery", "house", "bread"],
    ["banana", "fruit", "monkey"],
    ["banana", "bread bread", "banana"],
    ["bandage", "blood", "fabric"],
    ["bank", "house", "money"],
    ["bank", "house", "gold"],
    ["bank", "house", "safe"],
    ["barn", "cow", "house"],
    ["barn", "livestock", "house"],
    ["barn", "house", "hay"],
    ["bat", "mouse", "bird"],
    ["bat", "mouse", "sky"],
    ["batman", "bat", "human"],
    ["batter", "flour", "milk"],
    ["bayonet", "gun", "blade"],
    ["bayonet", "gun", "sword"],
    ["bbq", "campfire", "meat"],
    ["bbq", "campfire", "garden"],
    ["beach", "sea", "sand"],
    ["beach", "ocean", "sand"],
    ["beaver", "wild animal", "wood"],
    ["beaver", "wild animal", "dam"],
    ["bee", "flower", "wild animal"],
    ["beehive", "bee", "house"],
    ["beehive", "bee", "tree"],
    ["beer", "alcohol", "wheat"],
    ["bicycle", "wheel", "wheel"],
    ["bird", "air", "life"],
    ["bird", "life", "sky"],
    ["bird", "egg", "air"],
    ["bird", "egg", "sky"],
    ["birdhouse", "bird", "house"],
    ["black", "hole star", "pressure"],
    ["blade", "metal", "stone"],
    ["blender", "glass", "blade"],
    ["blender", "blade", "electricity"],
    ["blizzard", "snow", "snow"],
    ["blizzard", "snow", "storm"],
    ["blizzard", "snow", "wind"],
    ["blood", "human", "blade"],
    ["blueprint", "engineer", "paper"],
    ["boat", "water", "wood"],
    ["boiler", "steam", "metal"],
    ["bone", "corpse", "time"],
    ["bonsai", "tree tree", "pottery"],
    ["bonsai", "tree", "scissors"],
    ["book", "paper", "wood"],
    ["book", "paper", "story"],
    ["bread", "dough", "fire"],
    ["brick", "clay", "fire"],
    ["brick", "mud", "fire"],
    ["brick", "mud", "sun"],
    ["brick", "clay", "sun"],
    ["bridge", "river", "wood"],
    ["bridge", "river", "metal"],
    ["bridge", "river", "steel"],
    ["broom", "wood", "hay"],
    ["bullet", "gunpowder", "metal"],
    ["bulletproof", "vest bullet", "armour"],
    ["bus", "car", "car"],
    ["butcher", "human", "meat"],
    ["butter", "energy", "milk"],
    ["butter", "milk", "pressure"],
    ["butterfly", "flower", "wild animal"],
    ["cactus", "desert", "plant"],
    ["cactus", "sand", "plant"],
    ["cake", "dough", "candle"],
    ["camel", "desert", "wild animal"],
    ["camel", "desert", "horse"],
    ["camel", "livestock", "desert"],
    ["campfire", "fire", "wood"],
    ["candle", "wax", "thread"],
    ["candle", "wax", "fire"],
    ["candy", "cane sugar", "christmas tree"],
    ["cannon", "gunpowder", "pirate ship"],
    ["cannon", "gunpowder", "castle"],
    ["cape", "hero", "fabric"],
    ["car", "wheel", "metal"],
    ["caramel", "sugar", "fire"],
    ["carbon", "dioxide human", "oxygen"],
    ["carbon", "plant", "night"],
    ["carbon", "tree", "night"],
    ["carrot", "snowman", "vegetable"],
    ["carrot", "sun", "snowman"],
    ["cart", "wheel", "wood"],
    ["cashmere", "tool", "mountain goat"],
    ["cashmere", "thread", "mountain goat"],
    ["cashmere", "fabric", "mountain goat"],
    ["cashmere", "scissors", "mountain goat"],
    ["cashmere", "wool", "mountain goat"],
    ["castle", "house", "knight"],
    ["cat", "wild animal", "milk"],
    ["catnip", "cat", "plant"],
    ["cauldron", "metal", "witch"],
    ["cauldron", "steel", "witch"],
    ["cauldron", "fireplace", "witch"],
    ["cauldron", "campfire", "witch"],
    ["caviar", "hard roe", "human"],
    ["centaur", "horse", "human"],
    ["cereal", "wheat", "milk"],
    ["chain", "metal", "rope"],
    ["chain", "steel", "rope"],
    ["chainsaw", "axe", "electricity"],
    ["chameleon", "lizard", "rainbow"],
    ["charcoal", "fire", "wood"],
    ["cheese", "time", "milk"],
    ["cheeseburger", "cheese", "hamburger"],
    ["chicken", "egg", "livestock"],
    ["chicken", "livestock", "bird"],
    ["chicken", "bird", "farmer"],
    ["chicken", "soup water", "chicken"],
    ["chicken", "wing chicken", "bone"],
    ["chimney", "house", "fireplace"],
    ["chimney", "smoke", "brick"],
    ["chimney", "fireplace", "brick"],
    ["christmas", "stocking wool", "fireplace"],
    ["christmas", "tree light bulb", "tree"],
    ["christmas", "tree", "star"],
    ["cigarette", "tobacco", "paper"],
    ["city", "village", "village"],
    ["city", "skyscraper", "skyscraper"],
    ["clay", "sand", "mud"],
    ["clock", "time", "tool"],
    ["clock", "time", "wheel"],
    ["clock", "time", "electricity"],
    ["cloud", "air", "steam"],
    ["coal", "pressure", "plant"],
    ["coal", "sun", "snowman"],
    ["coconut", "palm", "fruit"],
    ["coconut", "milk coconut", "tool"],
    ["coconut", "milk", "coconut"],
    ["coffin", "wood", "corpse"],
    ["cold", "human", "rain"],
    ["computer", "electricity", "nerd"],
    ["computer", "wire", "nerd"],
    ["computer", "tool", "nerd"],
    ["computer", "mouse mouse", "computer"],
    ["confetti", "paper", "blade"],
    ["confetti", "paper", "scissors"],
    ["cookbook", "book", "recipe"],
    ["cookbook", "recipe", "recipe"],
    ["constellation", "star", "star"],
    ["cookie", "dough", "sugar"],
    ["corpse", "human", "gun"],
    ["corpse", "human", "grim reaper"],
    ["cotton", "plant", "cloud"],
    ["cow", "grass", "livestock"],
    ["crayon", "rainbow", "pencil"],
    ["crayon", "rainbow", "wax"],
    ["crow", "bird", "scarecrow"],
    ["crow", "bird", "field"],
    ["crown", "gold", "monarch"],
    ["crown", "metal", "monarch"],
    ["crystal", "ball witch", "glass"],
    ["crystal", "wizard", "glass"],
    ["cuckoo", "clock", "bird"],
    ["cyborg", "human", "robot"],
    ["cyclist", "bicycle", "human"],
    ["dam", "beaver", "river"],
    ["dam", "beaver", "tree"],
    ["dam", "beaver", "wood"],
    ["dam", "wall", "river"],
    ["darth", "vader jedi", "fire"],
    ["darth", "jedi", "lava"],
    ["day", "sun", "time"],
    ["day", "night", "sun"],
    ["day", "time", "night"],
    ["day", "sky", "sun"],
    ["desert", "sand", "sand"],
    ["desert", "sand", "cactus"],
    ["dew", "water", "grass"],
    ["dew", "fog", "grass"],
    ["diamond", "pressure", "coal"],
    ["dinosaur", "lizard", "time"],
    ["doctor", "human", "hospital"],
    ["dog", "wild animal", "human"],
    ["doge", "dog", "computer"],
    ["doghouse", "dog", "house"],
    ["don", "quixote windmill", "knight"],
    ["doughnut", "dough", "oil"],
    ["double", "rainbow! rainbow", "rainbow"],
    ["dough", "flour", "water"],
    ["dragon", "lizard", "fire"],
    ["drone", "airplane", "robot"],
    ["drum", "wood", "leather"],
    ["drunk", "human", "alcohol"],
    ["drunk", "beer", "human"],
    ["drunk", "human", "wine"],
    ["dry", "ice carbon dioxide", "cold"],
    ["dry", "ice", "carbon dioxide"],
    ["duck", "bird", "lake"],
    ["duck", "water", "bird"],
    ["duck", "bird", "pond"],
    ["duck", "time", "duckling"],
    ["duckling", "egg", "duck"],
    ["dune", "sand", "wind"],
    ["dune", "desert", "wind"],
    ["dune", "beach", "wind"],
    ["dust", "earth", "air"],
    ["dust", "sun", "vampire"],
    ["dust", "day", "vampire"],
    ["dynamite", "gunpowder", "wire"],
    ["eagle", "mountain", "bird"],
    ["earthquake", "earth", "energy"],
    ["earthquake", "earth", "wave"],
    ["eclipse", "sun", "moon"],
    ["egg", "life", "stone"],
    ["egg", "bird", "bird"],
    ["egg", "turtle", "turtle"],
    ["egg", "lizard", "lizard"],
    ["egg", "timer egg", "clock"],
    ["egg", "egg", "watch"],
    ["electric", "car car", "electricity"],
    ["electric", "eel fish", "electricity"],
    ["electrician", "human", "electricity"],
    ["electrician", "human", "wire"],
    ["electricity", "metal", "energy"],
    ["electricity", "solar cell", "sun"],
    ["electricity", "wind turbine", "wind"],
    ["electricity", "light", "solar cell"],
    ["email", "letter", "computer"],
    ["email", "letter", "internet"],
    ["energy", "air", "fire"],
    ["energy", "plant", "sun"],
    ["engineer", "human", "tool"],
    ["eruption", "volcano", "energy"],
    ["excalibur", "sword", "stone"],
    ["explosion", "gunpowder", "fire"],
    ["fabric", "thread", "tool"],
    ["fairy", "tale story", "monarch"],
    ["fairy", "story", "castle"],
    ["fairy", "knight", "story"],
    ["fairy", "dragon", "story"],
    ["family", "human", "house"],
    ["family", "tree tree", "family"],
    ["farm", "farmer", "house"],
    ["farm", "farmer", "barn"],
    ["farmer", "human", "plant"],
    ["farmer", "field", "human"],
    ["farmer", "human", "pitchfork"],
    ["faun", "goat", "human"],
    ["fence", "wall", "wood"],
    ["field", "earth", "farmer"],
    ["field", "earth", "tool"],
    ["fire", "extinguisher fire", "carbon dioxide"],
    ["fire", "pressure", "carbon dioxide"],
    ["fire", "metal", "carbon dioxide"],
    ["fireman", "human", "fire"],
    ["fireman", "human", "firetruck"],
    ["fireplace", "house", "campfire"],
    ["fireplace", "campfire", "brick"],
    ["fireplace", "campfire", "wall"],
    ["firetruck", "fireman", "car"],
    ["fireworks", "explosion", "sky"],
    ["fish", "hard roe", "time"],
    ["fish", "and chips fish", "french fries"],
    ["fishing", "rod tool", "fish"],
    ["fishing", "wood", "fish"],
    ["flamethrower", "fire", "gun"],
    ["flashlight", "tool", "light"],
    ["flood", "rain", "rain"],
    ["flood", "rain", "time"],
    ["flour", "wheat", "stone"],
    ["flour", "windmill", "wheat"],
    ["flower", "plant", "garden"],
    ["flute", "wood", "wind"],
    ["flying", "fish fish", "bird"],
    ["flying", "sky", "fish"],
    ["flying", "squirrel squirrel", "bird"],
    ["flying", "squirrel", "wind"],
    ["flying", "squirrel", "aeroplane"],
    ["flying", "sky", "squirrel"],
    ["fog", "earth", "cloud"],
    ["forest", "tree", "tree"],
    ["fortune", "cookie paper", "cookie"],
    ["fossil", "dinosaur", "time"],
    ["fossil", "dinosaur", "earth"],
    ["fossil", "stone", "dinosaur"],
    ["fountain", "statue", "water"],
    ["fox", "chicken", "wild animal"],
    ["frankenstein", "zombie", "electricity"],
    ["frankenstein", "electricity", "corpse"],
    ["french", "fries oil", "vegetable"],
    ["fridge", "metal", "cold"],
    ["fridge", "electricity", "cold"],
    ["fridge", "metal", "ice"],
    ["frog", "wild animal", "pond"],
    ["fruit", "tree", "farmer"],
    ["fruit", "sun", "tree"],
    ["fruit", "tree fruit", "tree"],
    ["galaxy", "star", "star"],
    ["garden", "plant", "plant"],
    ["garden", "flower", "flower"],
    ["garden", "plant", "grass"],
    ["garden", "house", "grass"],
    ["gardener", "human", "garden"],
    ["geyser", "steam", "earth"],
    ["ghost", "graveyard", "night"],
    ["ghost", "castle", "night"],
    ["gift", "santa", "christmas tree"],
    ["gift", "santa", "christmas stocking"],
    ["gift", "santa", "cookie"],
    ["gift", "santa", "chimney"],
    ["gift", "santa", "fireplace"],
    ["gingerbread", "house house", "dough"],
    ["gingerbread", "house", "gingerbread man"],
    ["gingerbread", "man life", "dough"],
    ["glacier", "ice", "mountain"],
    ["glass", "fire", "sand"],
    ["glass", "sand", "electricity"],
    ["glasses", "glass", "metal"],
    ["glasses", "glass", "glass"],
    ["gnome", "garden", "statue"],
    ["goat", "livestock", "mountain"],
    ["godzilla", "dinosaur", "city"],
    ["gold", "metal", "sun"],
    ["gold", "metal", "rainbow"],
    ["golem", "clay", "life"],
    ["granite", "lava", "pressure"],
    ["grass", "plant", "earth"],
    ["grave", "coffin", "earth"],
    ["grave", "corpse", "earth"],
    ["gravestone", "grave", "stone"],
    ["graveyard", "grave", "grave"],
    ["graveyard", "gravestone", "gravestone"],
    ["greenhouse", "plant", "glass"],
    ["greenhouse", "window", "window"],
    ["grenade", "explosion", "metal"],
    ["grilled", "cheese cheese", "toast"],
    ["grim", "reaper human", "scythe"],
    ["grim", "corpse", "scythe"],
    ["gun", "metal", "bullet"],
    ["gunpowder", "fire", "dust"],
    ["hail", "rain", "ice"],
    ["hail", "ice", "storm"],
    ["hail", "ice", "cloud"],
    ["ham", "meat", "smoke"],
    ["hamburger", "meat", "bread"],
    ["hammer", "metal", "wood"],
    ["hamster", "wheel", "mouse"],
    ["hard", "roe egg", "water"],
    ["hard", "egg", "sea"],
    ["hard", "egg", "ocean"],
    ["hard", "egg", "pond"],
    ["hard", "fish", "fish"],
    ["harp", "angel", "music"],
    ["hay", "farmer", "grass"],
    ["hay", "grass", "scythe"],
    ["hay", "grass", "sun"],
    ["hay", "bale hay", "hay"],
    ["hedge", "plant", "fence"],
    ["hedge", "leaf", "fence"],
    ["helicopter", "blade", "airplane"],
    ["helicopter", "windmill", "airplane"],
    ["herb", "plant", "sickness"],
    ["herb", "sickness", "leaf"],
    ["hero", "knight", "dragon"],
    ["hippo", "horse", "river"],
    ["hippo", "horse", "water"],
    ["honey", "bee", "flower"],
    ["honey", "bee", "beehive"],
    ["horizon", "sky", "earth"],
    ["horizon", "sea", "sky"],
    ["horizon", "ocean", "sky"],
    ["horse", "hay", "livestock"],
    ["horseshoe", "metal", "horse"],
    ["hospital", "house", "sickness"],
    ["hospital", "house", "ambulance"],
    ["hospital", "house", "doctor"],
    ["hourglass", "sand", "glass"],
    ["house", "wall", "wall"],
    ["human", "earth", "life"],
    ["hummingbird", "bird", "flower"],
    ["hurricane", "wind", "energy"],
    ["husky", "snow", "dog"],
    ["husky", "ice", "dog"],
    ["ice", "water", "cold"],
    ["iceberg", "sea", "ice"],
    ["iceberg", "ocean", "ice"],
    ["iceberg", "sea", "antarctica"],
    ["iceberg", "ocean", "antarctica"],
    ["ice", "cream milk", "ice"],
    ["ice", "cream truck car", "ice cream"],
    ["iced", "tea ice", "tea"],
    ["iced", "cold", "tea"],
    ["idea", "human", "light bulb"],
    ["idea", "light bulb", "nerd"],
    ["igloo", "house", "ice"],
    ["igloo", "house", "snow"],
    ["internet", "computer", "computer"],
    ["internet", "computer", "wire"],
    ["internet", "computer", "web"],
    ["isle", "ocean", "volcano"],
    ["isle", "volcano", "sea"],
    ["ivy", "plant", "wall"],
    ["jack-o'-lantern", "pumpkin", "fire"],
    ["jack-o'-lantern", "blade", "pumpkin"],
    ["jack-o'-lantern", "pumpkin", "candle"],
    ["jam", "juice", "sugar"],
    ["jedi", "lightsaber", "human"],
    ["jedi", "knight", "lightsaber"],
    ["jerky", "meat", "sun"],
    ["jerky", "meat", "salt"],
    ["juice", "water", "fruit"],
    ["juice", "pressure", "fruit"],
    ["keyboard", "cat cat", "music"],
    ["kite", "wind", "paper"],
    ["kite", "sky", "paper"],
    ["knight", "human", "armour"],
    ["lake", "water", "pond"],
    ["lake", "river", "dam"],
    ["lamp", "metal", "light bulb"],
    ["lasso", "cow", "rope"],
    ["lasso", "horse", "rope"],
    ["lava", "earth", "fire"],
    ["lava", "lamp lava", "lamp"],
    ["lawn", "mower grass", "tool"],
    ["lawn", "electricity", "scythe"],
    ["leaf", "tree", "wind"],
    ["leather", "cow", "blade"],
    ["leather", "pig", "blade"],
    ["lemonade", "fruit", "water"],
    ["letter", "paper", "pencil"],
    ["library", "house", "book"],
    ["life", "swamp", "energy"],
    ["life", "love", "time"],
    ["light", "light bulb", "electricity"],
    ["light", "electricity", "flashlight"],
    ["light", "bulb electricity", "glass"],
    ["lighthouse", "light", "house"],
    ["lighthouse", "light", "beach"],
    ["lighthouse", "light", "ocean"],
    ["lighthouse", "light", "sea"],
    ["lightsaber", "light", "sword"],
    ["lightsaber", "energy", "sword"],
    ["lightsaber", "electricity", "sword"],
    ["lion", "wild animal", "cat"],
    ["livestock", "farmer", "life"],
    ["livestock", "wild animal", "human"],
    ["livestock", "farmer", "wild animal"],
    ["lizard", "egg", "swamp"],
    ["log", "cabin wood", "house"],
    ["love", "human", "human"],
    ["lumberjack", "axe", "human"],
    ["lumberjack", "human", "chainsaw"],
    ["mac", "and cheese cheese", "pasta"],
    ["mailman", "human", "letter"],
    ["manatee", "cow", "sea"],
    ["map", "paper", "earth"],
    ["mars", "rust", "planet"],
    ["marshmallows", "sugar", "campfire"],
    ["mayonnaise", "egg", "oil"],
    ["meat", "cow", "tool"],
    ["meat", "livestock", "butcher"],
    ["meat", "cow", "butcher"],
    ["meat", "pig", "butcher"],
    ["meat", "pig", "tool"],
    ["meat", "blade", "livestock"],
    ["medusa", "human", "snake"],
    ["mermaid", "human", "fish"],
    ["metal", "fire", "stone"],
    ["meteor", "meteoroid", "atmosphere"],
    ["meteor", "sky", "meteoroid"],
    ["meteoroid", "stone", "space"],
    ["microscope", "glass", "bacteria"],
    ["microscope", "bacteria", "glasses"],
    ["milk", "farmer", "cow"],
    ["milk", "cow", "human"],
    ["milk", "shake milk", "ice cream"],
    ["minotaur", "human", "cow"],
    ["mirror", "glass", "metal"],
    ["mould", "time", "bread"],
    ["monarch", "human", "castle"],
    ["monarch", "excalibur", "human"],
    ["monarch", "crown", "human"],
    ["money", "paper", "gold"],
    ["monkey", "tree", "wild animal"],
    ["moon", "sky", "cheese"],
    ["moon", "sky", "stone"],
    ["moss", "plant", "stone"],
    ["moss", "algae", "stone"],
    ["moth", "moon", "butterfly"],
    ["moth", "night", "butterfly"],
    ["motorcycle", "bicycle", "energy"],
    ["motorcycle", "bicycle", "steel"],
    ["mountain", "earthquake", "earth"],
    ["mountain", "goat mountain", "goat"],
    ["mountain", "goat", "mountain range"],
    ["mountain", "range mountain", "mountain"],
    ["mouse", "cheese", "wild animal"],
    ["mousetrap", "wood", "cheese"],
    ["mousetrap", "metal", "cheese"],
    ["mud", "water", "earth"],
    ["mummy", "corpse", "pyramid"],
    ["music", "human", "flute"],
    ["music", "human", "sound"],
    ["narwhal", "unicorn", "ocean"],
    ["narwhal", "unicorn", "water"],
    ["narwhal", "sea", "unicorn"],
    ["needle", "metal", "thread"],
    ["needle", "metal", "hay"],
    ["nerd", "human", "glasses"],
    ["nessie", "story", "lake"],
    ["nest", "bird", "tree"],
    ["nest", "bird", "hay"],
    ["nest", "egg", "hay"],
    ["newspaper", "paper", "paper"],
    ["night", "moon", "time"],
    ["night", "time", "day"],
    ["night", "sky", "moon"],
    ["ninja", "shuriken", "human"],
    ["ninja", "turtle turtle", "ninja"],
    ["nut", "tree", "squirrel"],
    ["nut", "fruit", "squirrel"],
    ["oasis", "desert", "water"],
    ["obsidian", "lava", "water"],
    ["ocean", "sea", "sea"],
    ["ocean", "water", "sea"],
    ["oil", "sunflower", "pressure"],
    ["oil", "lamp clay", "oil"],
    ["oil", "potter", "oil"],
    ["oil", "oil", "rope"],
    ["oil", "glass", "oil"],
    ["oil", "fire", "oil"],
    ["omelette", "egg", "fire"],
    ["optical", "fiber wire", "light"],
    ["orchard", "fruit tree", "fruit tree"],
    ["orchard", "field", "fruit tree"],
    ["origami", "bird", "paper"],
    ["ostrich", "bird", "earth"],
    ["ostrich", "bird", "sand"],
    ["owl", "night", "bird"],
    ["owl", "bird", "wizard"],
    ["oxygen", "plant", "sun"],
    ["oxygen", "plant", "carbon dioxide"],
    ["ozone", "oxygen", "oxygen"],
    ["ozone", "oxygen", "electricity"],
    ["paint", "water", "rainbow"],
    ["paint", "water", "pencil"],
    ["palm", "isle", "tree"],
    ["palm", "tree", "beach"],
    ["paper", "wood", "pressure"],
    ["paper", "airplane airplane", "paper"],
    ["parachute", "pilot", "fabric"],
    ["parachute", "pilot", "umbrella"],
    ["parrot", "bird", "pirate"],
    ["pasta", "flour", "egg"],
    ["peacock", "bird", "rainbow"],
    ["pegasus", "bird", "horse"],
    ["pegasus", "sky", "horse"],
    ["pegasus", "bird", "unicorn"],
    ["pencil", "wood", "coal"],
    ["pencil", "wood", "charcoal"],
    ["pencil", "sharpener blade", "pencil"],
    ["penguin", "ice", "wild animal"],
    ["penguin", "ice", "bird"],
    ["penguin", "bird", "snow"],
    ["penicillin", "doctor", "mould"],
    ["perfume", "water", "rose"],
    ["perfume", "water", "flower"],
    ["perfume", "steam", "rose"],
    ["perfume", "steam", "flower"],
    ["perfume", "alcohol", "rose"],
    ["perfume", "alcohol", "flower"],
    ["petroleum", "fossil", "time"],
    ["petroleum", "fossil", "pressure"],
    ["phoenix", "fire", "bird"],
    ["picnic", "grass", "sandwich"],
    ["picnic", "beach", "sandwich"],
    ["pie", "dough", "fruit"],
    ["pig", "livestock", "mud"],
    ["pigeon", "bird", "city"],
    ["pigeon", "bird", "letter"],
    ["pigeon", "bird", "statue"],
    ["piggy", "bank pig", "money"],
    ["piggy", "pottery", "pig"],
    ["pillow", "cotton", "fabric"],
    ["pilot", "airplane", "human"],
    ["pilot", "seaplane", "human"],
    ["pinocchio", "wood", "life"],
    ["pipe", "tobacco", "wood"],
    ["piranha", "fish", "blood"],
    ["pirate", "sword", "sailor"],
    ["pirate", "sailor", "pirate ship"],
    ["pirate", "ship sailboat", "pirate"],
    ["pirate", "boat", "pirate"],
    ["pitchfork", "tool", "hay"],
    ["pizza", "cheese", "dough"],
    ["planet", "earth", "space"],
    ["plankton", "water", "life"],
    ["plankton", "sea", "life"],
    ["plant", "rain", "earth"],
    ["platypus", "beaver", "duck"],
    ["pond", "water", "garden"],
    ["popsicle", "juice", "ice"],
    ["pottery", "fire", "clay"],
    ["pottery", "clay", "wheel"],
    ["pottery", "clay", "tool"],
    ["pressure", "earth", "earth"],
    ["pressure", "air", "air"],
    ["printer", "paper", "computer"],
    ["prism", "glass", "rainbow"],
    ["pterodactyl", "air", "dinosaur"],
    ["pterodactyl", "bird", "dinosaur"],
    ["puddle", "snowman", "flamethrower"],
    ["puddle", "sun", "ice"],
    ["puddle", "sun", "snowman"],
    ["pumpkin", "vegetable", "fire"],
    ["pumpkin", "vegetable", "light"],
    ["pyramid", "desert", "stone"],
    ["pyramid", "desert", "grave"],
    ["quicksand", "sand", "swamp"],
    ["rabbit", "wild animal", "carrot"],
    ["rain", "water", "air"],
    ["rainbow", "rain", "sun"],
    ["rainbow", "rain", "light"],
    ["rat", "wild animal", "pirate ship"],
    ["rat", "sailboat", "wild animal"],
    ["recipe", "flour", "paper"],
    ["recipe", "paper", "baker"],
    ["reindeer", "santa", "wild animal"],
    ["reindeer", "livestock", "santa"],
    ["ring", "diamond", "metal"],
    ["ring", "diamond", "gold"],
    ["river", "mountain", "water"],
    ["river", "rain", "mountain"],
    ["robot", "metal", "life"],
    ["robot", "steel", "life"],
    ["robot", "life", "armour"],
    ["rocket", "airplane", "space"],
    ["roller", "coaster train", "mountain"],
    ["roller", "mountain", "cart"],
    ["roomba", "robot", "vacuum cleaner"],
    ["rope", "thread", "thread"],
    ["rose", "plant", "love"],
    ["rose", "flower", "love"],
    ["ruins", "time", "castle"],
    ["ruins", "time", "house"],
    ["ruler", "wood", "pencil"],
    ["rust", "air", "metal"],
    ["rust", "metal", "oxygen"],
    ["rust", "steel", "oxygen"],
    ["rust", "air", "steel"],
    ["rv", "car", "house"],
    ["saddle", "horse", "leather"],
    ["safe", "metal", "money"],
    ["safe", "metal", "gold"],
    ["safe", "steel", "money"],
    ["safe", "steel", "gold"],
    ["safety", "glasses explosion", "glasses"],
    ["safety", "tool", "glasses"],
    ["safety", "engineer", "glasses"],
    ["sailboat", "boat", "wind"],
    ["sailboat", "boat", "fabric"],
    ["sailor", "human", "boat"],
    ["sailor", "human", "sailboat"],
    ["salt", "sea", "sun"],
    ["salt", "ocean", "sun"],
    ["salt", "fire", "sea"],
    ["salt", "fire", "ocean"],
    ["sand", "air", "stone"],
    ["sand", "castle sand", "castle"],
    ["sandpaper", "sand", "paper"],
    ["sandstone", "stone", "sand"],
    ["sandstorm", "sand", "energy"],
    ["sandstorm", "sand", "storm"],
    ["sandstorm", "sand", "hurricane"],
    ["sandwich", "bread", "ham"],
    ["sandwich", "cheese", "bread"],
    ["sandwich", "bread", "bacon"],
    ["santa", "human", "christmas tree"],
    ["saturn", "ring", "planet"],
    ["scalpel", "blade", "doctor"],
    ["scalpel", "blade", "hospital"],
    ["scarecrow", "human", "hay"],
    ["scissors", "blade", "blade"],
    ["scorpion", "wild animal", "sand"],
    ["scorpion", "wild animal", "dune"],
    ["scythe", "blade", "grass"],
    ["scythe", "blade", "wheat"],
    ["seagull", "bird", "sea"],
    ["seagull", "bird", "ocean"],
    ["seagull", "bird", "beach"],
    ["seahorse", "horse", "sea"],
    ["seahorse", "ocean", "horse"],
    ["seahorse", "fish", "horse"],
    ["seal", "dog", "sea"],
    ["seaplane", "airplane", "water"],
    ["seaplane", "airplane", "ocean"],
    ["seaplane", "airplane", "sea"],
    ["seasickness", "sickness", "sea"],
    ["seasickness", "sickness", "ocean"],
    ["seasickness", "boat", "sickness"],
    ["seasickness", "steamboat", "sickness"],
    ["seasickness", "sailboat", "sickness"],
    ["seaweed", "plant", "sea"],
    ["seaweed", "plant", "ocean"],
    ["sewing", "machine electricity", "needle"],
    ["sewing", "robot", "needle"],
    ["shark", "ocean", "wild animal"],
    ["shark", "sea", "wild animal"],
    ["shark", "sea", "blood"],
    ["shark", "blood", "ocean"],
    ["sheep", "cloud", "livestock"],
    ["sheet", "music paper", "music"],
    ["shuriken", "star", "blade"],
    ["sickness", "human", "bacteria"],
    ["sickness", "human", "sickness"],
    ["sickness", "human", "rain"],
    ["skateboard", "snowboard", "wheel"],
    ["skeleton", "corpse", "time"],
    ["skeleton", "bone", "bone"],
    ["ski", "goggles glasses", "snow"],
    ["sky", "air", "cloud"],
    ["skyscraper", "house", "sky"],
    ["sledge", "snow", "cart"],
    ["sledge", "snow", "wagon"],
    ["smog", "smoke", "fog"],
    ["smog", "fog", "city"],
    ["smoke", "fire", "wood"],
    ["smoke", "signal campfire", "fabric"],
    ["smoke", "smoke", "fabric"],
    ["smoothie", "fruit", "blender"],
    ["snake", "wild animal", "wire"],
    ["snow", "steam", "cold"],
    ["snowball", "snow", "human"],
    ["snowboard", "wood", "snow"],
    ["snowboard", "snow", "surfer"],
    ["snow", "globe glass", "snow"],
    ["snow", "snow", "crystal ball"],
    ["snowman", "snow", "human"],
    ["snowman", "snowball", "snowball"],
    ["snowman", "snow", "carrot"],
    ["snowman", "snowball", "carrot"],
    ["snowmobile", "snow", "motorcycle"],
    ["snowmobile", "snow", "car"],
    ["soap", "oil", "ash"],
    ["soap", "bubble air", "soap"],
    ["soap", "water", "soap"],
    ["soda", "water", "carbon dioxide"],
    ["soda", "juice", "carbon dioxide"],
    ["solar", "cell sun", "tool"],
    ["solar", "system sun", "planet"],
    ["sound", "air", "wave"],
    ["space", "sky", "star"],
    ["space", "sun", "star"],
    ["space", "moon", "star"],
    ["spaceship", "airplane", "astronaut"],
    ["space", "station space", "house"],
    ["spaghetti", "thread", "pasta"],
    ["sphinx", "human", "lion"],
    ["spider", "wild animal", "thread"],
    ["sprinkles", "sugar", "confetti"],
    ["squirrel", "mouse", "tree"],
    ["star", "sky", "night"],
    ["star", "night", "telescope"],
    ["starfish", "fish", "star"],
    ["starfish", "sea", "star"],
    ["starfish", "ocean", "star"],
    ["statue", "stone", "tool"],
    ["statue", "human", "medusa"],
    ["steak", "fire", "cow"],
    ["steak", "meat", "bbq"],
    ["steam", "water", "fire"],
    ["steam", "water", "energy"],
    ["steamboat", "steam engine", "water"],
    ["steamboat", "steam engine", "boat"],
    ["steam", "engine boiler", "tool"],
    ["steam", "boiler", "wheel"],
    ["steel", "metal", "coal"],
    ["steel", "wool steel", "wool"],
    ["steel", "wire", "wool"],
    ["stethoscope", "tool", "doctor"],
    ["stone", "air", "lava"],
    ["storm", "energy", "cloud"],
    ["storm", "cloud", "electricity"],
    ["story", "human", "campfire"],
    ["sugar", "fruit", "energy"],
    ["sugar", "juice", "fire"],
    ["sugar", "juice", "energy"],
    ["sun", "fire", "sky"],
    ["sundial", "clock", "sun"],
    ["sunflower", "plant", "sun"],
    ["sunflower", "flower", "sun"],
    ["sunglasses", "sun", "glasses"],
    ["sunglasses", "beach", "glasses"],
    ["supernova", "explosion", "star"],
    ["surfer", "human", "wave"],
    ["sushi", "fish", "seaweed"],
    ["sushi", "caviar", "seaweed"],
    ["swamp", "mud", "plant"],
    ["swamp", "mud", "grass"],
    ["sweater", "wool", "tool"],
    ["sweater", "human", "wool"],
    ["swim", "goggles glasses", "water"],
    ["swimmer", "human", "swim goggles"],
    ["sword", "blade", "metal"],
    ["sword", "blade", "steel"],
    ["swordfish", "fish", "sword"],
    ["tank", "car", "armour"],
    ["tank", "car", "gun"],
    ["taser", "gun", "electricity"],
    ["tea", "water", "leaf"],
    ["telescope", "glass", "sky"],
    ["telescope", "glass", "star"],
    ["telescope", "glass", "space"],
    ["tent", "wood", "fabric"],
    ["tent", "house", "fabric"],
    ["the", "one ring volcano", "ring"],
    ["thread", "cotton", "tool"],
    ["thread", "wheel", "wool"],
    ["tide", "sea", "moon"],
    ["tide", "ocean", "moon"],
    ["time", "sand", "glass"],
    ["titanic", "steamboat", "iceberg"],
    ["toast", "sandwich", "fire"],
    ["toast", "bread", "fire"],
    ["tobacco", "plant", "fire"],
    ["tool", "metal", "human"],
    ["toucan", "bird", "rainbow"],
    ["tractor", "farmer", "car"],
    ["tractor", "field", "car"],
    ["train", "steam engine", "steel"],
    ["train", "steam engine", "metal"],
    ["train", "steam engine", "wheel"],
    ["train", "steam engine", "wagon"],
    ["treasure", "pirate", "treasure map"],
    ["treasure", "map pirate", "map"],
    ["tree", "plant", "time"],
    ["treehouse", "tree", "house"],
    ["trojan", "horse horse", "wood"],
    ["tsunami", "ocean", "earthquake"],
    ["tsunami", "sea", "earthquake"],
    ["tunnel", "engineer", "mountain"],
    ["turtle", "egg", "sand"],
    ["twilight", "day", "night"],
    ["tyrannosaurus", "rex meat", "dinosaur"],
    ["ufo", "rocket", "alien"],
    ["ufo", "airplane", "alien"],
    ["umbrella", "tool", "rain"],
    ["umbrella", "rain", "fabric"],
    ["unicorn", "rainbow", "horse"],
    ["unicorn", "rainbow", "life"],
    ["unicorn", "double rainbow!", "horse"],
    ["unicorn", "double rainbow!", "life"],
    ["vacuum", "cleaner electricity", "broom"],
    ["vampire", "human", "blood"],
    ["vampire", "human", "vampire"],
    ["vase", "plant", "pottery"],
    ["vase", "pottery", "flower"],
    ["vegetable", "field", "fruit"],
    ["village", "house", "house"],
    ["vinegar", "time", "wine"],
    ["vinegar", "air", "wine"],
    ["vinegar", "wine", "oxygen"],
    ["volcano", "lava", "earth"],
    ["volcano", "lava", "mountain"],
    ["volcano", "fire", "mountain"],
    ["vulture", "bird", "corpse"],
    ["wagon", "cart", "horse"],
    ["wall", "brick", "brick"],
    ["wallet", "leather", "money"],
    ["wand", "wizard", "wood"],
    ["warrior", "sword", "human"],
    ["watch", "human", "clock"],
    ["water", "gun water", "gun"],
    ["water", "lilly flower", "pond"],
    ["water", "pipe water", "pipe"],
    ["waterfall", "mountain", "river"],
    ["waterwheel", "water", "wheel"],
    ["waterwheel", "wheel", "river"],
    ["wave", "ocean", "wind"],
    ["wave", "sea", "wind"],
    ["wax", "bee", "beehive"],
    ["web", "spider", "thread"],
    ["werewolf", "wolf", "human"],
    ["werewolf", "werewolf", "human"],
    ["wheatfield,", "plant", "farmer"],
    ["wheel", "tool", "wood"],
    ["wild", "animal forest", "life"],
    ["wild", "boar pig", "wild animal"],
    ["wild", "pig", "forest"],
    ["wind", "pressure", "air"],
    ["wind", "air", "energy"],
    ["windmill", "house", "wind"],
    ["windmill", "wheel", "wind"],
    ["wind", "turbine windmill", "electricity"],
    ["window", "glass", "house"],
    ["wine", "fruit", "alcohol"],
    ["wire", "electricity", "metal"],
    ["witch", "human", "broom"],
    ["witch", "wizard", "broom"],
    ["wizard", "human", "energy"],
    ["wolf", "dog", "forest"],
    ["wolf", "wild animal", "moon"],
    ["wolf", "wild animal", "dog"],
    ["wood", "tool", "tree"],
    ["woodpecker", "bird", "wood"],
    ["wool", "sheep", "tool"],
    ["wool", "scissors", "sheep"],
    ["wrapping", "paper gift", "paper"],
    ["x-ray", "light", "bone"],
    ["x-ray", "light", "skeleton"],
    ["yak", "cow", "mountain"],
    ["yoda", "jedi", "swamp"],
    ["yogurt", "milk", "bacteria"],
    ["zombie", "corpse", "life"]
];

export default fusions;
